##### Import Library Pendukung

In [78]:
import pandas as pd
import numpy as np

##### Import Data Csv
###### Data Tugas 2 : Data Handphone

In [3]:
df = pd.read_csv("Data/Soal_Tugas2.csv")
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_class
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,0
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,1
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,1
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,1
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,1
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,1

##### Check Data Kosong
###### Outputnya 0 artinya Semua Data lengkap tidak ada yang kosong

In [4]:
df.isna().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_class      0
dtype: int64

##### Check Column/Variabel Data
###### Outputnya Nama-nama Colomn

In [7]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_class'],
      dtype='object')

##### Korelasi Antar Variabel
###### Berdasarkan Output dibawah : Korelasi Yang bernilai Positif artinya hubungan yang berbanding lurus atau bisa kita bilang berhubungan yang dimana hubungan antar variabel satu akan diikuti perubahan pada variabel dua secara teratur dan terarah. contohnya yang terlihat jelas adalah variabel Ram dengan variabel Price-list berkorelasi positif(Berhubungan yang dimana dengan tingginya Variabel Ram akan meningkatkan variabel price-list-nya.). untuk korelasi yang bernilai negatif adalah variabel yang berlawanan atau bisa dibilang tidak berhubungan. contohnya variabel dual_sim tinggi maka variabel battery_power akan cenderung rendah/ menurun.

In [5]:
df.corr()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_class
battery_power,1.000000,0.011252,0.011482,-0.041847,0.033334,0.015665,-0.004004,0.034085,0.001844,-0.029727,...,0.014901,-0.008402,-0.000653,-0.029959,-0.021421,0.052510,0.011522,-0.010516,-0.008343,0.149402
blue,0.011252,1.000000,0.021419,0.035198,0.003593,0.013443,0.041177,0.004049,-0.008605,0.036161,...,-0.006872,-0.041533,0.026351,-0.002952,0.000613,0.013934,-0.030236,0.010061,-0.021863,0.014001
clock_speed,0.011482,0.021419,1.000000,-0.001315,-0.000434,-0.043073,0.006545,-0.014364,0.012350,-0.005724,...,-0.014523,-0.009476,0.003443,-0.029078,-0.007378,-0.011432,-0.046433,0.019756,-0.024471,0.003494
dual_sim,-0.041847,0.035198,-0.001315,1.000000,-0.029123,0.003187,-0.015679,-0.022142,-0.008979,-0.024658,...,-0.020875,0.014291,0.041072,-0.011949,-0.016666,-0.039404,-0.014008,-0.017117,0.022740,0.009002
fc,0.033334,0.003593,-0.000434,-0.029123,1.000000,-0.016560,-0.029133,-0.001791,0.023618,-0.013356,...,-0.009990,-0.005176,0.015099,-0.011014,-0.012373,-0.006829,0.001793,-0.014828,0.020085,0.022464
four_g,0.015665,0.013443,-0.043073,0.003187,-0.016560,1.000000,0.008690,-0.001823,-0.016537,-0.029706,...,-0.019236,0.007448,0.007313,0.027166,0.037005,-0.046628,0.584246,0.016758,-0.017620,0.001001
int_memory,-0.004004,0.041177,0.006545,-0.015679,-0.029133,0.008690,1.000000,0.006886,-0.034214,-0.028310,...,0.010441,-0.008335,0.032813,0.037771,0.011731,-0.002790,-0.009366,-0.026999,0.006993,0.022132
m_dep,0.034085,0.004049,-0.014364,-0.022142,-0.001791,-0.001823,0.006886,1.000000,0.021756,-0.003504,...,0.025263,0.023566,-0.009434,-0.025348,-0.018388,0.017003,-0.012065,-0.002638,-0.028353,-0.018554
mobile_wt,0.001844,-0.008605,0.012350,-0.008979,0.023618,-0.016537,-0.034214,0.021756,1.000000,-0.018989,...,0.000939,0.000090,-0.002581,-0.033855,-0.020761,0.006209,0.001551,-0.014368,-0.000409,-0.007968
n_cores,-0.029727,0.036161,-0.005724,-0.024658,-0.013356,-0.029706,-0.028310,-0.003504,-0.018989,1.000000,...,-0.006872,0.024480,0.004868,-0.000315,0.025826,0.013148,-0.014733,0.023774,-0.009964,0.031260
pc,0.031441,-0.009952,-0.005245,-0.017143,0.644595,-0.005598,-0.033273,0.026282,0.018844,-0.001193,...,-0.018465,0.004196,0.028984,0.004938,-0.023819,0.014657,-0.001322,-0.008742,0.005389,0.027628
px_height,0.014901,-0.006872,-0.014523,-0.020875,-0.009990,-0.019236,0.010441,0.025263,0.000939,-0.006872,...,1.000000,0.510664,-0.020352,0.059615,0.043038,-0.010645,-0.031174,0.021891,0.051824,0.097951
px_width,-0.008402,-0.041533,-0.009476,0.014291,-0.005176,0.007448,-0.008335,0.023566,0.000090,0.024480,...,0.510664,1.000000,0.004105,0.021599,0.034699,0.006720,0.000350,-0.001628,0.030319,0.116703
ram,-0.000653,0.026351,0.003443,0.041072,0.015099,0.007313,0.032813,-0.009434,-0.002581,0.004868,...,-0.020352,0.004105,1.000000,0.015996,0.035576,0.010820,0.015795,-0.030455,0.022669,0.822354
sc_h,-0.029959,-0.002952,-0.029078,-0.011949,-0.011014,0.027166,0.037771,-0.025348,-0.033855,-0.000315,...,0.059615,0.021599,0.015996,1.000000,0.506144,-0.017335,0.012033,-0.020023,0.025929,0.009140
sc_w,-0.021421,0.000613,-0.007378,-0.016666,-0.012373,0.037005,0.011731,-0.018388,-0.020761,0.025826,...,0.043038,0.034699,0.035576,0.506144,1.000000,-0.022821,0.030941,0.012720,0.035423,0.035359
talk_time,0.052510,0.013934,-0.011432,-0.039404,-0.006829,-0.046628,-0.002790,0.017003,0.006209,0.013148,...,-0.010645,0.006720,0.010820,-0.017335,-0.022821,1.000000,-0.042688,0.017196,-0.029504,0.004394
three_g,0.011522,-0.030236,-0.046433,-0.014008,0.001793,0.584246,-0.009366,-0.012065,0.001551,-0.014733,...,-0.031174,0.000350,0.015795,0.012033,0.030941,-0.042688,1.000000,0.013917,0.004316,0.024638
touch_screen,-0.010516,0.010061,0.019756,-0.017117,-0.014828,0.016758,-0.026999,-0.002638,-0.014368,0.023774,...,0.021891,-0.001628,-0.030455,-0.020023,0.012720,0.017196,0.013917,1.000000,0.011917,-0.040001
wifi,-0.008343,-0.021863,-0.024471,0.022740,0.020085,-0.017620,0.006993,-0.028353,-0.000409,-0.009964,...,0.051824,0.030319,0.022669,0.025929,0.035423,-0.029504,0.004316,0.011917,1.000000,0.014001
price_class,0.149402,0.014001,0.003494,0.009002,0.022464,0.001001,0.022132,-0.018554,-0.007968,0.031260,...,0.097951,0.116703,0.822354,0.009140,0.035359,0.004394,0.024638,-0.040001,0.014001,1.000000

##### Insight Menarik

In [99]:
df[df.price_class >0]

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_class,Price_Grade,Battery_Power_Grade,False
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,17,3,7,1,10,0,1.0,Tinggi,Tinggi,1.0
2,563,1,0.5,1,2,1,41,0.9,145,5,...,11,2,9,1,10,0,1.0,Tinggi,lumayan,1.0
3,615,1,2.5,0,0,0,10,0.8,131,6,...,16,8,11,1,9,0,1.0,Tinggi,lumayan,1.0
6,1821,0,1.7,0,4,1,10,0.8,139,8,...,13,8,18,1,9,1,1.0,Tinggi,Sangat Tinggi,1.0
10,769,1,2.9,1,0,0,9,0.1,182,5,...,5,2,7,0,9,0,1.0,Tinggi,lumayan,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,1467,1,0.5,0,0,0,18,0.6,122,5,...,15,11,5,1,10,1,1.0,Tinggi,Tinggi,1.0
1994,858,0,2.2,0,1,0,50,0.1,84,1,...,17,16,3,1,10,0,1.0,Tinggi,lumayan,1.0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,11,10,16,1,10,1,1.0,Tinggi,Sangat Tinggi,1.0
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,9,1,5,1,10,0,1.0,Tinggi,Sangat Tinggi,1.0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,19,4,2,1,10,1,1.0,Tinggi,lumayan,1.0

In [21]:
df[(df.ram > 3000)]

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_class
6,1821,0,1.7,0,4,1,10,0.8,139,8,...,381,1018,3220,13,8,18,1,0,1,1
10,769,1,2.9,1,0,0,9,0.1,182,5,...,248,874,3946,5,2,7,0,0,0,1
11,1520,1,2.2,0,5,1,33,0.5,177,8,...,151,1005,3826,14,9,13,1,1,1,1
16,838,0,0.5,0,1,1,13,0.1,196,8,...,984,1850,3554,10,9,19,1,0,1,1
17,595,0,0.9,1,7,1,23,0.1,121,3,...,441,810,3752,10,2,18,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991,1882,0,2.0,0,11,1,44,0.8,113,8,...,4,743,3579,19,8,20,1,1,0,1
1993,1467,1,0.5,0,0,0,18,0.6,122,5,...,888,1099,3962,15,11,5,1,1,1,1
1994,858,0,2.2,0,1,0,50,0.1,84,1,...,528,1416,3978,17,16,3,1,1,0,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,1

In [83]:
df[(df.dual_sim > 0)]
df[df.dual_sim==0].sort_values("price_class",ascending=False)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_class,Price_Grade,Battery_Power_Grade
3,615,1,2.5,0,0,0,10,0.8,131,6,...,2769,16,8,11,1,0,0,1.0,Tinggi,lumayan
1234,578,1,0.5,0,9,1,62,0.3,170,5,...,2977,15,12,5,1,1,1,1.0,Tinggi,lumayan
1354,1998,1,1.2,0,8,0,31,0.6,196,8,...,2311,17,9,18,1,1,0,1.0,Tinggi,Sangat Tinggi
1345,947,1,0.5,0,1,1,51,0.1,144,2,...,2915,17,1,6,1,1,1,1.0,Tinggi,lumayan
1340,1469,0,0.5,0,3,1,58,0.5,150,7,...,1571,17,16,2,1,0,0,1.0,Tinggi,Tinggi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,618,1,1.0,0,9,1,13,0.1,80,4,...,1424,15,12,7,1,1,0,NaN,NaN,lumayan
1988,1547,1,2.9,0,2,0,57,0.4,114,1,...,1620,9,2,19,0,1,1,NaN,NaN,Sangat Tinggi
1989,586,0,2.8,0,2,0,15,0.2,83,3,...,2592,12,8,3,0,0,0,NaN,NaN,lumayan
1990,1617,1,2.4,0,8,1,36,0.8,85,1,...,296,5,3,7,1,0,0,NaN,NaN,Sangat Tinggi
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,869,18,10,19,1,1,1,NaN,NaN,Sangat Tinggi

##### Binning Data

In [94]:
df3=df
df3["Battery_Power_Grade"] = pd.cut(df3.battery_power, bins=[0,501,1000,1500,1998],
                      labels=['Rendah','lumayan','Tinggi','Sangat Tinggi'])
df3.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_class,Price_Grade,Battery_Power_Grade,False
0,842,0,2.2,0,1,0,7,0.6,188,2,...,9,7,19,0,0,1,NaN,NaN,lumayan,NaN
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,17,3,7,1,1,0,1.0,Tinggi,Tinggi,1.0
2,563,1,0.5,1,2,1,41,0.9,145,5,...,11,2,9,1,1,0,1.0,Tinggi,lumayan,1.0
3,615,1,2.5,0,0,0,10,0.8,131,6,...,16,8,11,1,0,0,1.0,Tinggi,lumayan,1.0
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,8,2,15,1,1,0,NaN,NaN,Sangat Tinggi,NaN

In [112]:
df3["touch_screen"] = df3["touch_screen"].replace(to_replace=np.nan, value=11)
df3["touch_screen"] = df3["touch_screen"].replace(to_replace=[1], value=12)
print(df3["touch_screen"])
x=df3["touch_screen"] = pd.cut(df3.touch_screen, bins=[0,11,12],labels=['Jelek','Bagus'])
print(x)

0       Jelek
1       Jelek
2       Jelek
3         NaN
4       Jelek
        ...
1995    Jelek
1996    Jelek
1997    Jelek
1998    Jelek
1999    Jelek
Name: touch_screen, Length: 2000, dtype: category
Categories (2, object): ['Jelek' < 'Bagus']

TypeError: '<' not supported between instances of 'int' and 'str'